function coneLocations = DebugConeFits()
    coneLocations = cell(1, 4);
    coneLocations{1} = edu.washington.riekelab.baudin.modules.SingleConeStimuli.Utils.Cone( ...
        [50 45], 5);
    coneLocations{2} = edu.washington.riekelab.baudin.modules.SingleConeStimuli.Utils.Cone( ...
        [170 30], 6);
    coneLocations{3} = edu.washington.riekelab.baudin.modules.SingleConeStimuli.Utils.Cone( ...
        [150 130], 7);
    coneLocations{4} = edu.washington.riekelab.baudin.modules.SingleConeStimuli.Utils.Cone( ...
        [45 140], 4);
end