function button = addFlankedByEmptyVertical(classType, parent, heights, varargin)
import appbox.*;
mainBox = uix.VBox( ...
    'Parent', parent);
uix.Empty( ...
    'Parent', mainBox);
button = classType( ...
    'Parent', mainBox, ...
    varargin{:});
uix.Empty( ...
    'Parent', mainBox);

mainBox.Heights = heights;
end