classdef StageSinusoidIncrementDecrement < ...
        edu.washington.riekelab.protocols.RiekeLabStageProtocol
    % Stage sinusoids in a center aperture or surround annulus.

    properties
        preTime = 500                         % ms
        stimTime = 2000                       % ms
        tailTime = 500                        % ms
        temporalFrequencies = 2               % Hz
        sinusoidContrasts = [0.1 0.25 0.5 1]  % fraction of mean
        lightMeans = [0.05 0.4]               % normalized Stage intensity
        stimulusRegion = 'center'             % center or surround
        apertureDiameter = 300                % center diameter (um)
        innerAnnulusDiameter = 400             % surround inner diameter (um)
        outerAnnulusDiameter = 800             % surround outer diameter (um)
        onlineAnalysis = 'exc'
        amp
        numberOfAverages = uint16(5)          % averages per condition
        interpulseInterval = 0                % s
    end

    properties (Hidden)
        ampType

        temporalFrequenciesType = ...
            symphonyui.core.PropertyType( ...
            'denserealdouble', 'matrix')

        sinusoidContrastsType = ...
            symphonyui.core.PropertyType( ...
            'denserealdouble', 'matrix')

        lightMeansType = ...
            symphonyui.core.PropertyType( ...
            'denserealdouble', 'matrix')

        stimulusRegionType = ...
            symphonyui.core.PropertyType( ...
            'char', 'row', {'center', 'surround'})

        onlineAnalysisType = ...
            symphonyui.core.PropertyType( ...
            'char', 'row', {'none', 'exc'})

        stimulusSequence
        currentTemporalFrequency
        currentSinusoidContrast
        currentLightMean

        epochTimers
    end


    methods

        function didSetRig(obj)

            didSetRig@edu.washington.riekelab.protocols.RiekeLabStageProtocol( ...
                obj);

            [obj.amp, obj.ampType] = ...
                obj.createDeviceNamesProperty('Amp');
        end


        function p = getPreview(obj, panel)

            if isempty(obj.rig.getDevices('Stage'))
                p = [];
                return;
            end

            p = io.github.stage_vss.previews.StagePreview( ...
                panel, ...
                @()obj.createPresentation(), ...
                'windowSize', ...
                obj.rig.getDevice('Stage').getCanvasSize());
        end


        function prepareRun(obj)

            prepareRun@edu.washington.riekelab.protocols.RiekeLabStageProtocol( ...
                obj);

            obj.validateParameters();

            obj.stimulusSequence = ...
                obj.makeStimulusSequence();

            % One timer per epoch. Using a separate timer for each epoch
            % avoids problems if Symphony prepares epochs ahead of time.
            obj.epochTimers = ...
                cell(size(obj.stimulusSequence, 1), 1);


            obj.showFigure( ...
                'symphonyui.builtin.figures.ResponseFigure', ...
                obj.rig.getDevice(obj.amp));

            obj.showFigure( ...
                'edu.washington.riekelab.chris.figures.FrameTimingFigure', ...
                obj.rig.getDevice('Stage'), ...
                obj.rig.getDevice('Frame Monitor'));


            if strcmp(obj.onlineAnalysis, 'exc')

                regionLabel = ...
                    sprintf('Stage %s', obj.stimulusRegion);

                obj.showFigure( ...
                    ['edu.washington.riekelab.chris.figures.', ...
                    'LedSinusoidMeanTraceFigure'], ...
                    obj.rig.getDevice(obj.amp), ...
                    'preTime', obj.preTime, ...
                    'lightMeans', obj.lightMeans, ...
                    'sinusoidContrasts', obj.sinusoidContrasts, ...
                    'temporalFrequencies', obj.temporalFrequencies, ...
                    'stimulusLabel', regionLabel);


                obj.showFigure( ...
                    ['edu.washington.riekelab.chris.figures.', ...
                    'LedSinusoidIncrementDecrementFigure'], ...
                    obj.rig.getDevice(obj.amp), ...
                    'preTime', obj.preTime, ...
                    'stimTime', obj.stimTime, ...
                    'lightMeans', obj.lightMeans, ...
                    'sinusoidContrasts', obj.sinusoidContrasts, ...
                    'temporalFrequencies', obj.temporalFrequencies, ...
                    'stimulusLabel', regionLabel);
            end
        end


        function prepareEpoch(obj, epoch)

            prepareEpoch@edu.washington.riekelab.protocols.RiekeLabStageProtocol( ...
                obj, epoch);


            % RiekeLabProtocol.prepareEpoch has already incremented
            % numEpochsPrepared, so it is the one-based sequence index.
            epochIndex = ...
                obj.numEpochsPrepared;


            totalEpochs = ...
                size(obj.stimulusSequence, 1);

            if epochIndex < 1 || ...
                    epochIndex > totalEpochs

                error( ...
                    ['Epoch index %d exceeds stimulusSequence ', ...
                    'length %d.'], ...
                    epochIndex, ...
                    totalEpochs);
            end


            fprintf( ...
                'Starting epoch %d/%d\n', ...
                epochIndex, ...
                totalEpochs);

            % Start a wall-clock timer for this epoch.
            obj.epochTimers{epochIndex} = ...
                tic;


            condition = ...
                obj.stimulusSequence(epochIndex, :);

            obj.currentLightMean = ...
                condition(1);

            obj.currentSinusoidContrast = ...
                condition(2);

            obj.currentTemporalFrequency = ...
                condition(3);


            device = ...
                obj.rig.getDevice(obj.amp);

            duration = ...
                (obj.preTime + obj.stimTime + obj.tailTime) / 1e3;

            epoch.addDirectCurrentStimulus( ...
                device, ...
                device.background, ...
                duration, ...
                obj.sampleRate);

            epoch.addResponse(device);


            epoch.addParameter( ...
                'currentLightMean', ...
                obj.currentLightMean);

            epoch.addParameter( ...
                'currentSinusoidContrast', ...
                obj.currentSinusoidContrast);

            epoch.addParameter( ...
                'currentTemporalFrequency', ...
                obj.currentTemporalFrequency);

            epoch.addParameter( ...
                'stimulusRegion', ...
                obj.stimulusRegion);

            epoch.addParameter( ...
                'apertureDiameter', ...
                obj.apertureDiameter);

            epoch.addParameter( ...
                'innerAnnulusDiameter', ...
                obj.innerAnnulusDiameter);

            epoch.addParameter( ...
                'outerAnnulusDiameter', ...
                obj.outerAnnulusDiameter);
        end


        function completeEpoch(obj, epoch)

            completeEpoch@edu.washington.riekelab.protocols.RiekeLabStageProtocol( ...
                obj, epoch);

            % The superclass has updated numEpochsCompleted at this point.
            epochIndex = ...
                obj.numEpochsCompleted;

            totalEpochs = ...
                size(obj.stimulusSequence, 1);

            if epochIndex >= 1 && ...
                    epochIndex <= totalEpochs && ...
                    numel(obj.epochTimers) >= epochIndex && ...
                    ~isempty(obj.epochTimers{epochIndex})

                elapsedTime = ...
                    toc(obj.epochTimers{epochIndex});

                fprintf( ...
                    'Epoch %d/%d completed in %.3f s\n', ...
                    epochIndex, ...
                    totalEpochs, ...
                    elapsedTime);
            else
                fprintf( ...
                    'Epoch %d/%d completed\n', ...
                    epochIndex, ...
                    totalEpochs);
            end
        end


        function p = createPresentation(obj)

            device = ...
                obj.rig.getDevice('Stage');

            canvasSize = ...
                device.getCanvasSize();

            lightMean = ...
                obj.presentationLightMean();

            contrast = ...
                obj.presentationContrast();

            frequency = ...
                obj.presentationFrequency();


            p = stage.core.Presentation( ...
                (obj.preTime + obj.stimTime + obj.tailTime) * 1e-3);

            p.setBackgroundColor(lightMean);


            modulatedArea = ...
                stage.builtin.stimuli.Ellipse();

            modulatedArea.position = ...
                canvasSize / 2;

            modulatedArea.color = ...
                lightMean;


            if strcmp(obj.stimulusRegion, 'center')

                diameterPix = ...
                    device.um2pix(obj.apertureDiameter);

            else

                diameterPix = ...
                    device.um2pix(obj.outerAnnulusDiameter);
            end


            modulatedArea.radiusX = ...
                diameterPix / 2;

            modulatedArea.radiusY = ...
                diameterPix / 2;

            p.addStimulus(modulatedArea);


            intensityController = ...
                stage.builtin.controllers.PropertyController( ...
                modulatedArea, ...
                'color', ...
                @(state)obj.sinusoidIntensity( ...
                state.time - obj.preTime * 1e-3, ...
                lightMean, ...
                contrast, ...
                frequency));

            p.addController(intensityController);


            visibleController = ...
                stage.builtin.controllers.PropertyController( ...
                modulatedArea, ...
                'visible', ...
                @(state)state.time >= obj.preTime * 1e-3 && ...
                state.time < ...
                (obj.preTime + obj.stimTime) * 1e-3);

            p.addController(visibleController);


            if strcmp(obj.stimulusRegion, 'surround')

                innerDiameterPix = ...
                    device.um2pix(obj.innerAnnulusDiameter);

                centerMask = ...
                    stage.builtin.stimuli.Ellipse();

                centerMask.position = ...
                    canvasSize / 2;

                centerMask.radiusX = ...
                    innerDiameterPix / 2;

                centerMask.radiusY = ...
                    innerDiameterPix / 2;

                centerMask.color = ...
                    lightMean;

                p.addStimulus(centerMask);
            end
        end


        function prepareInterval(obj, interval)

            prepareInterval@edu.washington.riekelab.protocols.RiekeLabStageProtocol( ...
                obj, interval);

            device = ...
                obj.rig.getDevice(obj.amp);

            interval.addDirectCurrentStimulus( ...
                device, ...
                device.background, ...
                obj.interpulseInterval, ...
                obj.sampleRate);
        end


        function tf = shouldContinuePreparingEpochs(obj)

            tf = ...
                obj.numEpochsPrepared < ...
                size(obj.stimulusSequence, 1);
        end


        function tf = shouldContinueRun(obj)

            tf = ...
                obj.numEpochsCompleted < ...
                size(obj.stimulusSequence, 1);
        end

    end


    methods (Access = private)

        function sequence = makeStimulusSequence(obj)

            [means, contrasts, frequencies] = ...
                ndgrid( ...
                obj.lightMeans(:), ...
                obj.sinusoidContrasts(:), ...
                obj.temporalFrequencies(:));

            conditions = [ ...
                means(:), ...
                contrasts(:), ...
                frequencies(:)];

            nConditions = ...
                size(conditions, 1);

            nRepeats = ...
                double(obj.numberOfAverages);

            sequence = zeros( ...
                nConditions * nRepeats, ...
                3);


            % Each repeat contains every condition exactly once,
            % randomized within that repeat.
            for repeat = 1:nRepeats

                rows = ...
                    (repeat - 1) * nConditions + ...
                    (1:nConditions);

                sequence(rows, :) = ...
                    conditions(randperm(nConditions), :);
            end
        end


        function validateParameters(obj)

            if obj.preTime <= 0

                error( ...
                    ['preTime must be greater than zero ', ...
                    'for baseline subtraction.']);
            end


            if obj.stimTime <= 0 || ...
                    obj.tailTime < 0

                error( ...
                    ['stimTime must be positive and ', ...
                    'tailTime cannot be negative.']);
            end


            if isempty(obj.temporalFrequencies) || ...
                    any(~isfinite(obj.temporalFrequencies(:))) || ...
                    any(obj.temporalFrequencies(:) <= 0)

                error( ...
                    ['temporalFrequencies must contain finite, ', ...
                    'positive values.']);
            end


            if isempty(obj.sinusoidContrasts) || ...
                    any(~isfinite(obj.sinusoidContrasts(:))) || ...
                    any(obj.sinusoidContrasts(:) < 0) || ...
                    any(obj.sinusoidContrasts(:) > 1)

                error( ...
                    ['sinusoidContrasts must contain finite ', ...
                    'fractions from zero to one.']);
            end


            if isempty(obj.lightMeans) || ...
                    any(~isfinite(obj.lightMeans(:))) || ...
                    any(obj.lightMeans(:) < 0) || ...
                    any(obj.lightMeans(:) > 1)

                error( ...
                    ['lightMeans must contain normalized ', ...
                    'Stage intensities from zero to one.']);
            end


            minima = ...
                obj.lightMeans(:) * ...
                (1 - max(obj.sinusoidContrasts(:)));

            maxima = ...
                obj.lightMeans(:) * ...
                (1 + max(obj.sinusoidContrasts(:)));


            if any(minima < 0) || ...
                    any(maxima > 1)

                error( ...
                    ['A lightMean/contrast combination exceeds ', ...
                    'the normalized Stage intensity range [0, 1].']);
            end


            if double(obj.numberOfAverages) < 1

                error( ...
                    ['numberOfAverages must be at least ', ...
                    'one per condition.']);
            end


            if obj.stimTime / 1000 * ...
                    min(obj.temporalFrequencies(:)) < 1

                error( ...
                    ['stimTime must contain at least one ', ...
                    'cycle at every temporal frequency.']);
            end


            if strcmp(obj.stimulusRegion, 'center')

                if ~isscalar(obj.apertureDiameter) || ...
                        ~isfinite(obj.apertureDiameter) || ...
                        obj.apertureDiameter <= 0

                    error( ...
                        ['apertureDiameter must be a positive ', ...
                        'finite scalar for a center stimulus.']);
                end

            else

                if ~isscalar(obj.innerAnnulusDiameter) || ...
                        ~isscalar(obj.outerAnnulusDiameter) || ...
                        ~isfinite(obj.innerAnnulusDiameter) || ...
                        ~isfinite(obj.outerAnnulusDiameter) || ...
                        obj.innerAnnulusDiameter < 0 || ...
                        obj.outerAnnulusDiameter <= ...
                        obj.innerAnnulusDiameter

                    error( ...
                        ['For a surround stimulus, diameters must ', ...
                        'be finite scalars with 0 <= inner < outer.']);
                end
            end
        end


        function lightMean = presentationLightMean(obj)

            if isempty(obj.currentLightMean)
                lightMean = obj.lightMeans(1);
            else
                lightMean = obj.currentLightMean;
            end
        end


        function contrast = presentationContrast(obj)

            if isempty(obj.currentSinusoidContrast)
                contrast = obj.sinusoidContrasts(1);
            else
                contrast = obj.currentSinusoidContrast;
            end
        end


        function frequency = presentationFrequency(obj)

            if isempty(obj.currentTemporalFrequency)
                frequency = obj.temporalFrequencies(1);
            else
                frequency = obj.currentTemporalFrequency;
            end
        end

    end


    methods (Static, Access = private)

        function intensity = sinusoidIntensity( ...
                time, ...
                lightMean, ...
                contrast, ...
                frequency)

            intensity = ...
                lightMean * ...
                (1 + contrast * sin(2 * pi * frequency * time));
        end

    end

end
