classdef ConductanceFilenameLookup
    properties (Constant)
        CONDUCTANCE_FILENAMES = containers.Map( ...
            {'foveal midget', 'peripheral midget', 'peripheral parasol'}, ...
            {'foveal_midget.mat', ...
            'peripheral_midget.mat', ...
            'peripheral_parasol.mat'});
    end
end